version: '3.4'
services:
  web:
    image: okteto/django:latest
     build:
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command:
      - python manage.py runserver 0.0.0.0:8080
    
