version: '3.0'
services:
  web:
    image: okteto/django:latest
    build: .
    command: ./run_web.sh
    volumes:
      - .:/app
    ports:
      - "8080:8080"

  worker:
    image: okteto/django:latest
    build: .
    command: ./run_celery.sh
    volumes:
      - .:/app

  db:
    image: postgres:9.4
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ifrs
    ports:
      - "5432:5432"
