version: '3.0'
services:
  web:
    image: okteto/django:latest
    build: .
    command: ./run_web.sh
    volumes:
      - .:/app
    ports:
      - "8080:8080"

  worker:
    image: okteto/django:latest
    build: .
    command: ./run_celery.sh
    volumes:
      - .:/app