version: '3.0'
services:
  web:
    image: okteto/anaconda:latest
    build: .
    command: ./run_web.sh
    volumes:
      - .:/app
    ports:
      - "8000:8080"
    depends_on:
      - db
  
  db:
    image: postgres:9.4
    hostname: db
    environment:
      - POSTGRES_USER=okteto
      - POSTGRES_PASSWORD=okteto
      - POSTGRES_DB=okteto
    ports:
      - "5432:5432"